language: android
jdk: oraclejdk8
android:
  components:
    #- tools
    #- platform-tools
    #- build-tools-23.0.1
    #- android-23
    #- extra-android-support
    #- extra-android-m2repository
    #- extra-google-m2repository
    #- extra-google-google_play_services
    #- sys-img-x86-android-10
    #- sys-img-x86-android-18
    #- sys-img-x86-android-19
  licenses:
    - android-sdk-license-bcbbd656
    - '.*intel.+'
git:
  depth: 3
# Not working for public repositories :(
cache:
  - apt
  - directories:
    - $HOME/.m2
    - $HOME/.gradle
    - $DOWNLOADS_HOME
env:
  matrix:
    #- ANDROID_API=23 ANDROID_ABI=armeabi-v7a
    - ANDROID_API=22 ANDROID_ABI=armeabi-v7a NEED_UPLOAD_APK=true
    - ANDROID_API=21 ANDROID_ABI=armeabi-v7a
    - ANDROID_API=19 ANDROID_ABI=armeabi-v7a
    #- ANDROID_API=14 ANDROID_ABI=armeabi-v7a
    #- ANDROID_API=10 ANDROID_ABI=armeabi
  global:
    - secure: Kq5NpWlyXvAvzZ5UUwAxtooG7Cwtdnzh1fhCNqE2Lx2441w9aEGntd5+ffCCTCF4orRHlFIbqfE4/D1YlH6cJtP9hW37SPI8swe3r6Zyfjftakbe3ld72bVfq0f2zx5T4zln63jppMs+XxKNYjg8UswC+9C8Vi2LeJdPUC/Zdzs=
    - secure: X6INcg26b1Bm48QDfDDhLnbRJm5tOffr+AWVcXkgaSbYybqPvYQmSLX7ai1ArCzDgTYqz12tUTVLgrgMlsXkQGFj41hoD+IEtO9zJOmHdtwUDkkh4yVvNwoJ7TTT/N7wL7ZAU556khWy76sS7/biv4iPohCy//R91LWki2d1240=
    - secure: WusDaL9feBHMAz/DydbMngPkSvVMxnKnkrJgXi+LuG3FuWEA5fgDIdEgB3mADUCQZRuNYUJ61H7nUYFttPZ1yZOe107ETDCk0/UpIJ7PzPr62v7uVNyqPijVBufHI9iJ+bxyVW3Nt4reocJ3yqRxwP0z9FV+aEsn8Ke1S8YaKzU=
    - REPO="RandoApp/Rando-android"
    - DOWNLOADS_HOME=$HOME/downloads
    - APPS_HOME=$HOME/apps
    - CI_HOME=$HOME/build/$REPO

before_install:
  # Install lftp for apk upload:
  - sudo apt-get update -qq
  - sudo apt-get install -qq lftp
  # Install tree for directory structure debug
  #- sudo apt-get install -qq tree

  # Install base Android SDK
  - cd ${HOME}
  - if [ ! -d $DOWNLOADS_HOME ]; then mkdir $DOWNLOADS_HOME; fi

  # Install Gradle
#  - if [ ! -f $DOWNLOADS_HOME/gradle.zip ]; then  wget http://services.gradle.org/distributions/gradle-2.14-bin.zip -O $DOWNLOADS_HOME/gradle.zip > /dev/null; fi
 # - if [ ! -d $APPS_HOME/gradle-2.14 ]; then unzip --qq $DOWNLOADS_HOME/gradle.zip -d $APPS_HOME; fi
  #- export GRADLE_HOME=$APPS_HOME/gradle-2.14
  #- export PATH=$GRADLE_HOME/bin:$PATH

  # Install NDK
  - cd $DOWNLOADS_HOME
  - if [ ! -f $DOWNLOADS_HOME/android-ndk.zip ]; then  wget https://dl.google.com/android/repository/android-ndk-r11c-linux-x86_64.zip -O $DOWNLOADS_HOME/android-ndk.zip > /dev/null; fi
  - if [ ! -d $APPS_HOME/android-ndk-r11c ]; then unzip -qq android-ndk.zip -d $APPS_HOME; fi
  - export ANDROID_NDK_HOME=$APPS_HOME/android-ndk-r11c
  - export PATH=$ANDROID_NDK_HOME/bin:$PATH

  # Install required components.
  # For a full list, run `android list sdk -a --extended`
  - echo yes | android update sdk --filter android-23 --all --no-ui --force
  - echo yes | android update sdk --filter android-$ANDROID_API --all --no-ui --force
  - echo yes | android update sdk --filter build-tools-23.0.1 --all --no-ui --force
  - echo yes | android update sdk --filter extra-google-m2repository --all --no-ui --force
  - echo yes | android update sdk --filter extra-android-m2repository --all --no-ui --force
  - echo yes | android update sdk --filter sys-img-armeabi-v7a-android-$ANDROID_API --all --no-ui --force

before_script:
# Create and start emulator
  - android list targets
  - echo no | android create avd --force -n test -t android-$ANDROID_API --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  #- ci/wait_for_emulator.sh
  - adb shell input keyevent 82 &

  # Create gradle.properties with secret stroke password:
  - cd ${CI_HOME}
  - echo "keyStorePassword=$KEY_STROKE_PASSWORD" > gradle.properties
  - echo "reportsUser=\"$REPORTS_USER\"" >> gradle.properties
  - echo "reportsPassword=\"$REPORTS_PASSWORD\"" >> gradle.properties
  #Download rando.keystore:
  - lftp "sftp://travis:$APK_UPLOAD_PASS@rando4.me" -e "get rando.keystore; ; bye";
  - mv rando.keystore $HOME/.android/

script:
  - ./gradlew connectedAndroidTest coveralls --stacktrace
  - if [ $NEED_UPLOAD_APK ]; then ./gradlew assembleRelease; fi

after_script:
    - if [ $NEED_UPLOAD_APK ]; then lftp "sftp://travis:$APK_UPLOAD_PASS@rando4.me" -e "put build/outputs/apk/Rando-android-release.apk; bye"; fi
