language: android

addons:
  apt:
    packages:
    - lftp

env:
  matrix:
    - ANDROID_API=27 ANDROID_ABI=armeabi-v7a
    - ANDROID_API=25 ANDROID_ABI=armeabi-v7a
    - ANDROID_API=22 ANDROID_ABI=armeabi-v7a NEED_UPLOAD_APK=true
    - ANDROID_API=19 ANDROID_ABI=armeabi-v7a
    - ANDROID_API=16 ANDROID_ABI=armeabi-v7a
  global:
    - secure: Kq5NpWlyXvAvzZ5UUwAxtooG7Cwtdnzh1fhCNqE2Lx2441w9aEGntd5+ffCCTCF4orRHlFIbqfE4/D1YlH6cJtP9hW37SPI8swe3r6Zyfjftakbe3ld72bVfq0f2zx5T4zln63jppMs+XxKNYjg8UswC+9C8Vi2LeJdPUC/Zdzs=
    - secure: IjasoSr9pGo8xks18EVz7Oj8EtoJnOf3cac1T563CRHtGNHVOHjGxvTJKITNYGtRnBHDJKeTa5avz30UQc2xwBpCutBkigV2+Op5KWkMTmzftXOOwwJ1ofw8jNo7dgAWkwvm3io5juIwJsqCuqd6+xJIb44tlN109GLhqAKvfzU=
    - secure: Cd4d2sNECC+yLA1k7RRA23UHp6mvOmx8+bOs94NtRvesPWL8hzE6zx/ilNABa7cUyRwYJOpDrrrQj9Z6eUTS4NHvBqeqXaRhhIKXZ5IrkTYh7LZjloFhd0WRk+CPlHWYGiLjoVoMXowmaU2h0ycRnNtmBs4XuZDvO/Wv4T5k9Bk=

    - REPO="RandoApp/Rando-android"
    - DOWNLOADS_HOME=$HOME/downloads
    - APPS_HOME=$HOME/apps
    - CI_HOME=$HOME/build/$REPO

android:
  components:
    - tools
    #- build-tools-27.0.3
    - platform-tools
    #- android-27
    #- extra-android-m2repository
    #- extra-google-m2repository
    - android-$ANDROID_API
    - sys-img-armeabi-v7a-android-$ANDROID_API

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - '.*intel.+'
    - 'android-sdk-license-.+'
    - '.+'
git:
  depth: 3
# Not working for public repositories :(
cache:
  - apt
  - directories:
    - $HOME/.m2
    - $HOME/.gradle
    - $DOWNLOADS_HOME
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/

before_install:
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager "build-tools;27.0.3"
  - export EMULATOR="system-images;android-${EMULATOR_API_LEVEL};${EMULATOR_TAG};${EMULATOR_ABI}" # Used to install/create emulator
  - echo 'count=0' > /home/travis/.android/repositories.cfg # Avoid warning

install:
  # Install lftp for apk upload:
  #- sudo apt-get update -qq
  #- sudo apt-get install -qq lftp
  #- sudo apt-get install sshpass
  # Install tree for directory structure debug
  #- sudo apt-get install -qq tree


  # Install base Android SDK
  - cd ${HOME}
  - if [ ! -d $DOWNLOADS_HOME ]; then mkdir $DOWNLOADS_HOME; fi
  #- echo yes | sdkmanager ndk-bundle
  #- echo yes | sdkmanager "cmake;3.6.4111459"
  #- echo yes | sdkmanager "lldb;3.0"

  # Install Gradle
  - if [ ! -f $DOWNLOADS_HOME/gradle.zip ]; then  wget http://services.gradle.org/distributions/gradle-4.1-all.zip -O $DOWNLOADS_HOME/gradle.zip > /dev/null; fi
  - if [ ! -d $APPS_HOME/gradle-4.1 ]; then unzip --qq $DOWNLOADS_HOME/gradle.zip -d $APPS_HOME; fi
  - export GRADLE_HOME=$APPS_HOME/gradle-4.1
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -version

#Clean up some space
  - sdkmanager --list
  - sdkmanager --uninstall "build-tools;25.0.2"
  # Create gradle.properties with secret stroke password:
  - cd ${CI_HOME}
  - echo "keyStorePassword=$KEY_STROKE_PASSWORD" > gradle.properties
  - echo "googleAppId=\"$GOOGLE_APP_ID\"" >> gradle.properties
  - echo "googleApiKey=\"$GOOGLE_API_KEY\"" >> gradle.properties
  - echo "org.gradle.jvmargs=-Xmx1536M" >> gradle.properties
  # Create fabric.properties key and secret
  - echo "apiKey=$CRASHLITICS_KEY" > fabric.properties
  - echo "apiSecret=$CRASHLITICS_SECRET" >> fabric.properties
  #Download rando.keystore:
  - lftp "sftp://travis:$APK_UPLOAD_PASS@rando4.me" -e "get rando.keystore; ; bye";
  #- export SSHPASS=$APK_UPLOAD_PASS
  #- sshpass scp travis@rando4.me:/home/travis/rando.keystore $HOME/.android/
  - mv rando.keystore $HOME/.android/
  #- sshpass scp travis@rando4.me:/home/travis/google-services.json ./
  - lftp "sftp://travis:$APK_UPLOAD_PASS@rando4.me" -e "get google-services.json; ; bye";
# Create and start emulator
  # For a full list of android targets, run "android list targets"
  #- android list targets
  #- android list sdk -a -e
  - echo no | android create avd --force -n test -t android-$ANDROID_API --abi $ANDROID_ABI
  - emulator -memory 1536 -avd test -no-window &
  - travis_wait 10 android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - gradle build jacocoTestReport connectedAndroidTest -x lint --stacktrace

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - if [ $NEED_UPLOAD_APK ]; then gradle assembleRelease -x lint; fi
  #- tree build/outputs
  - if [ $NEED_UPLOAD_APK ]; then lftp "sftp://travis:$APK_UPLOAD_PASS@rando4.me" -e "put build/outputs/apk/release/Rando-android-release.apk; bye"; fi

after_failure:
  #- sudo apt-get install -qq pandoc
  #- pandoc /home/travis/build/RandoApp/Rando-android/build/reports/androidTests/connected/index.html -t plain | sed -n '/^Failed tests/,/default-package/p'